from ninja_taisen.objects.types import Card, Category, Team

MR1 = Card(Team.monkey, Category.rock, 1)
MR2 = Card(Team.monkey, Category.rock, 2)
MR3 = Card(Team.monkey, Category.rock, 3)
MP1 = Card(Team.monkey, Category.paper, 1)
MP2 = Card(Team.monkey, Category.paper, 2)
MP3 = Card(Team.monkey, Category.paper, 3)
MS1 = Card(Team.monkey, Category.scissors, 1)
MS2 = Card(Team.monkey, Category.scissors, 2)
MS3 = Card(Team.monkey, Category.scissors, 3)
MJ4 = Card(Team.monkey, Category.joker, 4)

WR1 = Card(Team.wolf, Category.rock, 1)
WR2 = Card(Team.wolf, Category.rock, 2)
WR3 = Card(Team.wolf, Category.rock, 3)
WP1 = Card(Team.wolf, Category.paper, 1)
WP2 = Card(Team.wolf, Category.paper, 2)
WP3 = Card(Team.wolf, Category.paper, 3)
WS1 = Card(Team.wolf, Category.scissors, 1)
WS2 = Card(Team.wolf, Category.scissors, 2)
WS3 = Card(Team.wolf, Category.scissors, 3)
WJ4 = Card(Team.wolf, Category.joker, 4)
